#!/usr/bin/env bash
# apply-oauth-secrets.sh
# ---------------------------------------------------------------------------
# Writes Google Sign-In iOS client credentials into git-ignored Secrets.xcconfig.
#
# Usage (after creating an iOS OAuth client in Google Cloud Console):
#   ./scripts/apply-oauth-secrets.sh \
#     "123456789-abcdef.apps.googleusercontent.com" \
#     "com.googleusercontent.apps.123456789-abcdef"
#
# Or interactive:
#   ./scripts/apply-oauth-secrets.sh
# ---------------------------------------------------------------------------
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SECRETS="$ROOT/Config/Secrets.xcconfig"

CLIENT_ID="${1:-}"
REDIRECT_SCHEME="${2:-}"

if [[ -z "$CLIENT_ID" ]]; then
  echo "Paste the iOS OAuth Client ID (ends with .apps.googleusercontent.com):"
  read -r CLIENT_ID
fi
if [[ -z "$REDIRECT_SCHEME" ]]; then
  # Derive reversed client id when the user only pastes the client id.
  if [[ "$CLIENT_ID" == *.apps.googleusercontent.com ]]; then
    PREFIX="${CLIENT_ID%.apps.googleusercontent.com}"
    REDIRECT_SCHEME="com.googleusercontent.apps.${PREFIX}"
    echo "Derived redirect scheme: $REDIRECT_SCHEME"
  else
    echo "Paste the iOS URL scheme (reversed client id, starts with com.googleusercontent.apps.):"
    read -r REDIRECT_SCHEME
  fi
fi

if [[ "$CLIENT_ID" != *.apps.googleusercontent.com ]]; then
  echo "error: client id must end with .apps.googleusercontent.com" >&2
  exit 1
fi
if [[ "$REDIRECT_SCHEME" != com.googleusercontent.apps.* ]]; then
  echo "error: redirect scheme must start with com.googleusercontent.apps." >&2
  exit 1
fi

cat > "$SECRETS" <<EOF
// Secrets.xcconfig  (git-ignored — do NOT commit real values)
// Generated by scripts/apply-oauth-secrets.sh for project firetap-truesolutions
// ---------------------------------------------------------------------------

GOOGLE_OAUTH_CLIENT_ID = ${CLIENT_ID}
GOOGLE_OAUTH_REDIRECT_SCHEME = ${REDIRECT_SCHEME}
EOF

echo "Wrote $SECRETS"
if command -v "$HOME/.local/bin/xcodegen" >/dev/null 2>&1; then
  (cd "$ROOT" && "$HOME/.local/bin/xcodegen" generate)
  echo "Regenerated FireTap.xcodeproj"
fi
echo "Next: open Xcode → Clean Build Folder → Run."
